name: weather_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  searchfield: ^0.8.4
  shared_preferences: ^2.2.0
  bloc_concurrency: ^0.2.2
  country_flags: ^2.1.0
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  open_weather_api: 
    path: packages/open_weather_api
  weather_api:
    path: packages/weather_api

flutter:
  uses-material-design: true

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
          weight: 800
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/WeatherIcons.ttf
