name: open_weather_api
description: Api for https://openweathermap.org/api.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  freezed_annotation: ^2.4.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  weather_api:
    path: ../weather_api

dev_dependencies:
  build_runner: ^2.4.6  
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1
